# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  projects: 'ChemistWareHouse.Pizza.Api/*.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure service connection>'
    appType: 'webAppLinux'
    appName: 'bikash-technical'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

### Deploy React Project ####
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/ChemistWareHouse.Pizza.UI'
    verbose: false 

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/ChemistWareHouse.Pizza.UI'
    customCommand: 'run build'
    verbose: false

- task: AzureCLI@2
  displayName: "Admin Web - Clean Azure Blob before copy"
  inputs:
    # azureSubscription: $(azureSubscription)
    scriptType: ps
    scriptLocation: "inlineScript"
    inlineScript: "az storage blob delete-batch --account-name chemistwarehouse --source '$web'"

- task: AzureFileCopy@3
  displayName: "Admin Web - Deploy"
  inputs:
    SourcePath: "$(System.DefaultWorkingDirectory)/ChemistWareHouse.Pizza.UI/build"
    # azureSubscription: $(azureSubscription)
    Destination: "AzureBlob"
    storage: "chemistwarehouse"
    ContainerName: "$web"


### End React Project ####
